# Generated by Django 3.0.1 on 2019-12-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='githubprojects',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='github_project_category', to='posts.Category'),
        ),
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_category', to='posts.Category'),
        ),
    ]
