# Generated by Django 3.0.1 on 2019-12-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191226_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubprojects',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='github_project_category', to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='post_category', to='posts.Category'),
        ),
    ]
